### ISSUE TITLE
How does this module manage zones ? 

### ISSUE THREAD

**Issue by hdep** [theforeman/puppet-dns#124]
Hi,

I'm sorry but I'm a bit confuse with the capabilites of this module.
I was able to create a zone exemple.com. 
But I would like that my DNS records to be manage by puppet too.

I didn't see anything in the code which allow me to create dns records into a specific zone.

Can you please explain to me what this module manage exactly ? 

Thank you !

**Comment by ekohl** [comment]
The intended zone management with this module is by using `nsupdate`. Direct management of zones isn't something support in a nice way. We do use concat to build the file so you can add more fragments but since we hardcode `replace => false` this isn't really usable. The workaround is passing `manage_file` to false and manage it yourself similar to https://github.com/theforeman/puppet-dns/blob/c8b619f13899f98238186eec19bc53550b76441b/manifests/zone.pp#L81-L89

If you have ideas on how to do this nicer, I'd be interested to hear your thoughts.

**Comment by ekohl** [comment]
> change the replace by a variable in order to let the user decide if he wants the module manage the zone,

This does make sense. Even if we don't add a records parameter you could already append it with `concat::fragment`

> add in the template a simple hash like :

There are multiple ways of doing the hash. It's a nice chance to clean up the header with the default values we set.

**Comment by ekohl** [comment]
I opened https://github.com/theforeman/puppet-dns/pull/125 for the `$replace` parameter but I now realize that the content isn't done through `concat::fragment` so in itself it's probably not that useful.
